exposing signup/login endpoints
Omoefe-Ugboma/flexicon_forum_app_back_01 pull request #2
Opened 2023-10-23 18:58 UTC by sope-mosuro

endpoints created waiting for review

2023-10-23 18:59 UTC, sope-mosuro commented
![](https://github.trello.services/images/mini-trello-icon.png) [Expose signup and login endpoints](https://trello.com/c/eUSNeHHP/5-expose-signup-and-login-endpoints)

2023-10-23 20:18 UTC, adelaykay requested changes
Please add comments.

2023-10-23 20:48 UTC, adelaykay approved these changes

2023-10-25 13:32 UTC, Omoefe-Ugboma approved these changes

2023-10-25 13:33 UTC, merged