User Schema and Model
Omoefe-Ugboma/flexicon_forum_app_back_01 pull request #3
Opened 2023-10-23 19:45 UTC by Lumryanrea

The User Schema and model has been created.

2023-10-25 13:30 UTC, Omoefe-Ugboma approved these changes

2023-10-25 13:31 UTC, Omoefe-Ugboma approved these changes

2023-10-25 13:31 UTC, Omoefe-Ugboma approved these changes

2023-10-25 17:54 UTC, Omoefe-Ugboma approved these changes

2023-10-27 09:05 UTC, adelaykay requested changes
1.  Please implement discussed changes in schema which include:
    a. A community model and references to it in other models
    b. A thread model and references to it in other models
    c. Agreed upon modifications to existing models and constraints based on reference diagram.
![FSHub_ER (1)](https://github.com/Omoefe-Ugboma/flexicon_forum_app_back_01/assets/36890804/c1501106-366c-4d40-a291-878a980fb552)

2023-10-29 16:31 UTC, adelaykay approved these changes
All good.

2023-10-29 16:32 UTC, merged