Chukwuemeka/user registration and login
Omoefe-Ugboma/flexicon_forum_app_back_01 pull request #4
Opened 2023-10-30 21:06 UTC by mxsurft

Registration and Login features created.

2023-10-30 21:07 UTC, mxsurft commented
![](https://github.trello.services/images/mini-trello-icon.png) [User Login - Part 1](https://trello.com/c/bUbsvcju/3-user-login-part-1)

2023-10-30 21:07 UTC, mxsurft commented
![](https://github.trello.services/images/mini-trello-icon.png) [User Registration - Part 1](https://trello.com/c/IAhsD7nH/2-user-registration-part-1)

2023-10-30 22:40 UTC, adelaykay requested changes
1. Remove Console Logs
2. Rename token property in json response to accessToken
3. Remove unused mongoose import in authentication.js

2023-10-31 10:55 UTC, mxsurft commented
1. Remove Console Logs - **Done**
2. Rename token property in json response to accessToken - - **Done**
3. Remove unused mongoose import in authentication.js - **Done**

2023-10-31 11:50 UTC, adelaykay approved these changes

2023-10-31 11:50 UTC, adelaykay commented on README.md
> +Also create a MONGO_URI variable in your env file and assign an appropriate database string.
Awesome, awesome. 😉

2023-10-31 14:32 UTC, Omoefe-Ugboma approved these changes

2023-10-31 14:33 UTC, Omoefe-Ugboma approved these changes

2023-10-31 21:29 UTC, merged